### ISSUE TITLE
Request: Place .exe inside a zip

### ISSUE THREAD

**Issue by ChemGuy1611** [brunoanc/DOOMLauncher#4]
Hello,

Thank you for your work on this launcher and updating it to support the April 2024 version of DOOM.

I am the author of the Vortex Mod Manger extension for DOOM, and I have a small request to make it easier for me to download this mod from my extension for users to enjoy.

My request is if you could package the release of the .exe file inside a compressed zip. The reason for this is that if I simply download the .exe file, the mod manager will actually extract the .exe to its internal code files. If it is in a zip, it will extract the zip and leave the .exe file.

Thanks again!

**Comment by brunoanc** [comment]
Done, thank you!
